version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin15
      POSTGRES_PASSWORD: adgzcb
      POSTGRES_DB: serve_chat
    volumes:
      - ./data:/var/lib/postgresql/data
    
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - PORT=8000
    depends_on:
      - db