apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Docker\Serve_Chat\Serve_Chat\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
