apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Docker\Serve_Chat\Serve_Chat\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: replica
  name: replica
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: replica
status:
  loadBalancer: {}
