apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Docker\Serve_Chat\Serve_Chat\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: replica
  name: replica
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: replica
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Docker\Serve_Chat\Serve_Chat\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: replica
    spec:
      containers:
        - image: mongo
          name: replica
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: replica-claim0
      restartPolicy: Always
      volumes:
        - name: replica-claim0
          persistentVolumeClaim:
            claimName: replica-claim0
status: {}
